## **Read from csv and create Data Frame**

In [13]:
import pandas as pd
df=pd.read_csv("synthetic_logs.csv")

In [14]:
df.head()

,timestamp,source,log_message,target_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status

In [15]:
df.target_label.unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

## **Create vecors for each tokens**

In [16]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Your log data
logs = df["log_message"].tolist()

# Convert text → vectors
vectorizer = TfidfVectorizer(
    max_features=2000, 
    ngram_range=(1,2),
    stop_words=None
)

log_vectors = vectorizer.fit_transform(logs)

In [17]:
type(log_vectors)

scipy.sparse._csr.csr_matrix

In [18]:
log_vectors[1].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 2000))

In [19]:
uniq_types = df.target_label.unique()

In [20]:
print(uniq_types.size)

9

## **Clustering the messages**

In [21]:
# Clustering
# As uniq_types is 9 we are chosing 10 clusters

kmeans = KMeans(n_clusters=10, random_state=42)
df["cluster"] = kmeans.fit_predict(log_vectors)

In [22]:
df.head()

,timestamp,source,log_message,target_label,cluster
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,7
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,7
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0

In [23]:
df.cluster.unique()

array([0, 7, 3, 6, 2, 5, 8, 9, 1, 4], dtype=int32)

In [24]:
df[df.cluster == 8]

,timestamp,source,log_message,target_label,cluster
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,8
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,8
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,8
57,9/14/2025 3:03,AnalyticsEngine,User User395 logged in.,User Action,8
85,3/13/2025 2:11,ModernHR,User User225 logged in.,User Action,8
...,...,...,...,...,...
2275,3/13/2025 17:17,AnalyticsEngine,User User755 logged out.,User Action,8
2317,03-07-2025 05:44,BillingSystem,System reboot initiated by user User724.,System Notification,8
2323,12-01-2025 18:17,ThirdPartyAPI,User User882 logged out.,User Action,8
2353,06-10-2025 19:38,AnalyticsEngine,User User536 logged in.,User Action,8
2360,05-01-2025 04:21,ThirdPartyAPI,System reboot initiated by user User876.,System Notification,8

## **Calsify the logs using RegX**

In [28]:
import re

# Define patterns (pattern, label)
patterns = [
    (r"\b(GET|POST|PUT|DELETE|PATCH)\b.*\b(200|201|204|301|302|400|401|403|404|500|502|503)\b", "HTTP_STATUS"),

    (r"\b(login|logged in|signin|authenticated).*(success|successful)\b", "USER_ACTION"),

    (r"\b(login|authentication|signin).*(fail|failed|error|unsuccessful|denied)\b", "SECURITY_ALERT"),

    (r"\b(access|permission|authorization).*(denied|forbidden|unauthorized|rejected)\b", "SECURITY_ALERT"),

    (r"\b(db|database).*(fail|error|timeout|unreachable|lost|issue)\b", "ERROR"),

    (r"\b(exception|fatal).*(null|undefined|pointer|crash)?\b", "CRITICAL_ERROR"),

    (r"\b(memory|cpu|disk|resource).*(high|low|exceed|spike|leak|full|usage)\b", "RESOURCE_USAGE"),

    (r"\b(service|server|application).*(start|started|stop|stopped|restart|restarted)\b", "SYSTEM_NOTIFICATION"),

    (r"\b(file|resource|document).*(not found|missing|unavailable)\b", "ERROR"),

    (r"\b(timeout|timed out|took too long|delayed)\b", "ERROR"),

    (r"\b(api|endpoint|service).*(fail|error|unavailable|down)\b", "ERROR"),

    (r"\b(payment|transaction|billing|invoice).*(fail|error|declined|pending)\b", "WORKFLOW_ERROR"),

    (r"\b(deprecated|obsolete|no longer supported|will be removed)\b", "DEPRECATION_WARNING"),

    (r"\b(config|configuration|setting).*(invalid|missing|error|incorrect)\b", "ERROR"),

    (r"\b(suspicious|attack|intrusion|malicious|threat)\b", "SECURITY_ALERT"),

    (r"\b(job|task|queue|process).*(start|started|complete|completed|fail|failed)\b", "SYSTEM_NOTIFICATION"),

    (r"\b(cache).*(miss|fail|error|evict|clear)\b", "RESOURCE_USAGE"),
]

# Compile all patterns once
compiled_patterns = [(re.compile(p, re.IGNORECASE), label) for p, label in patterns]


def classify(log_message: str) -> str:
    for pattern, label in compiled_patterns:
        if pattern.search(log_message):
            return label
    return "UNKNOWN"

In [ ]:
if __name__ == "__main__":
    logs = [
        "GET /api/users HTTP/1.1 200",
        "User john logged in successfully",
        "Login failed due to invalid credentials",
        "Database connection timeout error",
        "Out of memory error in service",
        "Payment failed for transaction 12345",
        "Suspicious activity detected from IP 192.168.1.1"
    ]

    for log in logs:
        print(f"{log}  --->  {classify(log)}")

GET /api/users HTTP/1.1 200  --->  HTTP_STATUS
User john logged in successfully  --->  UNKNOWN
Login failed due to invalid credentials  --->  SECURITY_ALERT
Database connection timeout error  --->  ERROR
Out of memory error in service  --->  UNKNOWN
Payment failed for transaction 12345  --->  UNKNOWN
Suspicious activity detected from IP 192.168.1.1  --->  SECURITY_ALERT

In [30]:
logs = [
    "System initialized successfully",
    "Login attempt unsuccessful",
    "Latency recorded at 200ms",
    "Order created successfully"
]

for log in logs:
    print(classify(log))

UNKNOWN
USER_ACTION
UNKNOWN
UNKNOWN

In [31]:
df['regx_labels'] = df['log_message'].apply(classify)

In [32]:
df_non_regx = df[df['regx_labels']=="UNKNOWN"].copy()

In [33]:
df_non_regx.shape

(1300, 6)

## **Classify the logs that has less training data**

In [34]:
# Get target_labels that have fewer than 5 rows
label_counts = df['target_label'].value_counts()
rare_labels = label_counts[label_counts < 5].index

In [35]:

rare_labels
type(df)

pandas.DataFrame

In [36]:
training_df = df[~df['target_label'].isin(rare_labels)]

In [37]:
training_df.shape

(2403, 6)

In [ ]:
from fastembed import TextEmbedding
import numpy as np

model = TextEmbedding(model_name="BAAI/bge-small-en")

log_messages = training_df["log_message"].tolist()

embeddings = np.array(list(model.embed(log_messages)))

In [39]:
embeddings[0]

array([-8.37230757e-02, -5.99146442e-05, -6.89718733e-03, -4.57780883e-02,
        1.24226091e-02, -1.70555431e-02, -1.69710349e-02, -2.31087990e-02,
        1.26650427e-02, -7.44740758e-03,  9.16670263e-03, -4.88223732e-02,
        4.20215391e-02,  1.76765379e-02,  1.37700886e-02,  1.87685788e-02,
       -1.06409835e-02, -1.49161378e-02, -4.63518896e-04,  1.00147948e-02,
        4.85533997e-02, -4.79787476e-02, -1.28038684e-02, -1.87198818e-02,
       -7.66243488e-02,  4.90789860e-02, -1.21257622e-02, -1.96023881e-02,
       -2.53855325e-02, -1.84138536e-01, -3.95326428e-02, -5.17901406e-02,
       -2.85508614e-02, -2.39621177e-02,  2.92274319e-02, -2.80292388e-02,
       -1.16248708e-02,  1.82595141e-02, -2.30680145e-02,  4.86318544e-02,
        6.81315958e-02,  1.15745338e-02, -3.06101441e-02, -9.72947478e-03,
       -1.65466238e-02, -4.20337729e-02, -2.30020080e-02, -2.70570000e-03,
        1.50465397e-02, -5.78415440e-03, -8.70369934e-03,  1.09547088e-02,
       -2.94803968e-03,  5.20899147e-02,  3.11451666e-02,  2.31707953e-02,
        5.72601706e-02,  7.46115670e-02,  3.01468391e-02, -8.66374839e-03,
        1.76898185e-02,  1.43291941e-02, -1.97428674e-01,  7.24836811e-02,
        1.97442807e-02, -5.61422203e-03,  1.94953848e-03, -5.88385686e-02,
       -8.33212305e-03, -7.71151809e-03, -3.16631943e-02,  1.22895744e-02,
        3.01974695e-02,  5.03710508e-02,  9.58070531e-03,  1.43176569e-02,
        2.54636388e-02,  4.73969476e-03,  5.84263988e-02,  1.44923935e-02,
       -1.07883625e-02,  1.61098409e-02, -1.35620246e-02, -3.35645825e-02,
       -2.58217864e-02, -8.81608017e-03,  1.89169440e-02,  6.76740110e-02,
        5.50038740e-02, -1.12872301e-02, -5.60715199e-02, -3.10589336e-02,
        3.61328609e-02,  6.33197743e-03, -4.65243720e-02,  9.26065352e-03,
       -2.51512113e-03,  2.49855053e-02, -6.10061921e-02,  6.00340128e-01,
       -9.14399803e-04,  2.51786243e-02, -9.64142289e-03, -6.91335974e-03,
        3.46974842e-02, -2.19475161e-02, -2.07935385e-02, -2.18289010e-02,
       -3.03488690e-02, -1.63027570e-02,  8.48974194e-03, -1.24006951e-02,
        4.25373316e-02, -7.20640123e-02, -2.46538036e-03,  3.72939743e-02,
       -1.58735216e-02, -1.70227010e-02, -6.79545924e-02,  4.26842012e-02,
       -2.47068051e-02,  1.27645684e-02,  2.49311738e-02, -2.13192776e-02,
        2.49140486e-02, -1.48387989e-02,  3.58383916e-02,  4.31164764e-02,
       -2.06869119e-03,  4.03276570e-02,  2.88257655e-02, -1.30332364e-02,
       -3.03134322e-02, -4.99400869e-02,  1.38953654e-02,  7.45830638e-03,
        2.15245541e-02,  1.98763572e-02, -2.92052459e-02,  8.66880734e-03,
       -6.15217797e-02, -9.36117619e-02, -3.39214839e-02, -2.59247459e-02,
       -1.35823200e-02,  9.84610841e-02, -9.88465641e-03,  1.92736071e-02,
       -7.70799257e-03, -1.60772391e-02, -4.27609943e-02,  3.06577701e-02,
       -1.76517945e-02, -3.58465128e-02, -1.60803273e-02,  2.49728020e-02,
        4.87783588e-02,  2.14007888e-02, -3.01953424e-02, -2.98060030e-02,
       -1.64566804e-02, -5.57008348e-02, -1.75231528e-02,  5.17224036e-02,
        2.40071919e-02, -1.10133678e-01, -6.48908503e-03,  4.18432914e-02,
        3.94462747e-03,  2.21798848e-03,  2.47987779e-03, -3.39696929e-03,
       -8.31028633e-03, -4.34718803e-02,  7.82367587e-02, -3.15974765e-02,
       -4.02612844e-03, -8.64172447e-03,  8.78649298e-03,  5.64412819e-03,
       -1.34881949e-02, -1.14553992e-03, -2.38856692e-02, -8.27231631e-03,
        2.53512524e-02, -2.32817754e-02, -8.95071775e-03,  2.41076411e-03,
        1.37491748e-02,  3.49242263e-03, -2.57303342e-02, -3.92396078e-02,
       -4.58387993e-02, -2.60371668e-03,  6.85225381e-03, -7.00328033e-03,
       -1.88425425e-02,  3.21237743e-02,  2.13243645e-02, -5.20377569e-02,
        1.12964019e-01,  3.47331762e-02, -1.43774841e-02,  2.94591654e-02,
       -2.57872697e-02,  1.28992284e-02, -3.24099772e-02, -9.62956902e-03,
        6.03085104e-03,  1.19787585e-02, -2.75348723e-02,  2.92687607e-03,
        2.19530575e-02,  6.69047190e-03, -3.04323435e-02,  1.26400124e-03,
       -1.68869104e-02,  1.57064609e-02,  1.12237968e-02,  3.29578966e-02,
       -1.00990236e-02, -4.05006157e-03, -4.73374538e-02, -2.23319188e-01,
        1.34879891e-02,  1.56631172e-02, -5.29560894e-02,  5.88403270e-03,
       -1.89878456e-02,  3.40040810e-02, -3.53951268e-02,  3.63365524e-02,
        5.68977632e-02,  8.85256529e-02,  3.39167528e-02,  1.62406489e-02,
       -6.96849171e-03,  7.81739410e-03,  5.03406078e-02,  4.25383821e-02,
       -1.56014878e-02, -3.50064486e-02, -1.44018596e-02, -2.46094745e-02,
       -4.61453013e-02, -2.80532930e-02, -2.30097622e-02,  2.71165892e-02,
       -2.54899953e-02,  1.73166275e-01, -3.68762692e-03,  4.68962528e-02,
       -6.17472008e-02,  2.09323559e-02,  3.85443121e-02, -1.42092453e-02,
       -8.22388977e-02, -1.57209302e-04,  3.73658985e-02,  2.97469459e-02,
        2.99780723e-02,  2.33073309e-02,  4.52785753e-03, -2.39596106e-02,
        3.98709625e-02,  1.70787610e-03, -3.85783464e-02,  1.67772546e-02,
       -1.88891329e-02, -5.35263505e-04, -1.30739333e-02, -5.04309945e-02,
        2.14030687e-02,  1.68876499e-02,  9.12608986e-04,  1.78953800e-02,
        5.53834252e-02,  2.78709992e-03, -3.73301506e-02, -4.68552932e-02,
       -3.15997526e-02,  3.28192785e-02, -9.20155365e-03,  1.40149249e-02,
       -3.47493626e-02, -3.49798636e-03, -5.14563434e-02,  1.11512765e-02,
       -2.02438962e-02,  1.61975827e-02, -1.64554343e-02,  5.61131276e-02,
       -2.63132174e-02, -2.74025500e-02,  1.86422560e-02, -2.42907330e-02,
       -4.31064144e-03, -1.68266147e-02, -2.52299551e-02,  2.80163940e-02,
       -1.55536169e-02,  1.83145516e-02, -7.08010420e-03,  2.51840390e-02,
       -4.44543082e-03,  3.72734778e-02,  2.09436603e-02,  1.71835292e-02,
       -8.70867749e-04,  2.04014461e-02,  6.21146597e-02, -9.12481267e-03,
       -8.18779878e-03, -2.24054959e-02,  1.63152386e-02, -3.39402677e-03,
       -4.39172760e-02,  5.34766763e-02, -6.74954150e-03, -2.96051294e-01,
        5.09498194e-02,  2.06245743e-02,  2.39209533e-02,  4.23993217e-03,
       -1.30509073e-02,  2.22134050e-02,  3.24020274e-02, -3.33093405e-02,
        4.56924038e-03,  6.28270209e-04,  6.25419244e-02, -3.41400951e-02,
        1.42505821e-02,  8.25783517e-03,  2.76284777e-02,  5.35960011e-02,
       -3.57395671e-02,  1.02571743e-02, -8.41528084e-03,  2.60600587e-03,
       -1.60592445e-03,  1.58334449e-01,  8.35710764e-03, -2.47138349e-04,
        1.83819532e-02,  1.18934531e-02,  5.45738265e-02, -2.15109496e-04,
       -1.25097912e-02, -2.53953952e-02, -8.43637809e-03, -1.27253868e-03,
        3.08150984e-02,  3.20460834e-02,  4.66874652e-02,  1.08431783e-02,
        6.30061049e-03,  6.24197186e-04, -3.68860108e-03,  7.04915682e-03,
        3.68841253e-02,  8.46219435e-03,  2.39196159e-02,  1.23935211e-02,
       -2.83241719e-02, -6.23059087e-03, -3.10279373e-02,  1.39871044e-02,
        5.67343831e-03, -3.58580276e-02, -2.35963110e-02,  2.57025398e-02,
       -6.47735037e-03,  2.28387304e-02,  2.98893126e-03, -6.90663746e-03,
       -1.81946177e-02, -1.91294141e-02, -1.42783010e-02,  2.54930966e-02,
       -5.37183806e-02,  3.22255567e-02, -5.49744852e-02,  4.43329290e-03],
      dtype=float32)

In [40]:
embeddings.shape

(2403, 384)

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = embeddings
y = training_df["target_label"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2, stratify=y
)

clf_model = LogisticRegression(max_iter=1000, random_state=2)
clf_model.fit(X_train, y_train)

y_pred = clf_model.predict(X_test)

In [53]:

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy ", accuracy)

Accuracy  0.9916839916839917

In [58]:
import joblib

joblib.dump(clf_model, "../log_classifier.joblib")

['../log_classifier.joblib']